# Generated by Django 5.2.7 on 2025-12-21 18:37

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('co_no', models.CharField(help_text='Company or contract number (unique identifier)', max_length=50, unique=True)),
                ('project_name', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('project_manager', models.CharField(max_length=100)),
                ('project_manager_email', models.EmailField(max_length=254)),
                ('sales_person', models.CharField(max_length=100)),
                ('sales_person_email', models.EmailField(max_length=254)),
                ('sales_value', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('ter', models.DecimalField(decimal_places=2, help_text='Total Estimated Revenue?', max_digits=15, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='TER')),
                ('eff', models.DecimalField(decimal_places=2, help_text='Efficiency?', max_digits=5, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='EFF')),
                ('factor', models.DecimalField(decimal_places=2, help_text='Multiplier factor?', max_digits=5, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('budget', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('margin', models.DecimalField(decimal_places=2, help_text='Planned profit margin percentage', max_digits=5, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('forecast', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['co_no'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('PROJECT_MANAGEMENT', 'Project Management'), ('MECHANICAL_DESIGN', 'Mechanical Design'), ('ELECTRICAL_DESIGN', 'Electrical Design'), ('IN_HOUSE_COMMISSIONING', 'In-House Commissioning'), ('MECHANICAL_INSTALLATION', 'Mechanical Installation'), ('ELECTRICAL_INSTALLATION', 'Electrical Installation'), ('ON_SITE_COMMISSIONING', 'On-Site Commissioning'), ('SUPPORT_FUNCTION', 'Support Function')], max_length=50)),
                ('hourly_rate', models.DecimalField(decimal_places=2, help_text='Hourly rate for this department (project-specific)', max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('budget_hours', models.DecimalField(decimal_places=2, default=0, help_text='Budgeted hours for this department', max_digits=12, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('budget_cost', models.DecimalField(decimal_places=2, default=0, help_text='Budgeted cost (hours * rate)', max_digits=15, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('forecast_hours', models.DecimalField(decimal_places=2, default=0, help_text='Forecasted hours', max_digits=12, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('forecast_cost', models.DecimalField(decimal_places=2, default=0, help_text='Forecasted cost', max_digits=15, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='core.project')),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'ordering': ['name'],
                'unique_together': {('project', 'name')},
            },
        ),
        migrations.CreateModel(
            name='SubDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Sub-department code (e.g., MEC, KMA_KHP)', max_length=50)),
                ('name', models.CharField(help_text='Full description (e.g., Mechanical Design Coordinator)', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_departments', to='core.department')),
            ],
            options={
                'verbose_name': 'Sub-Department',
                'verbose_name_plural': 'Sub-Departments',
                'ordering': ['code'],
                'unique_together': {('department', 'code')},
            },
        ),
    ]
