# Generated by Django 5.2.7 on 2025-12-21 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_project_co_no_alter_project_eff_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subdepartment',
            name='name',
        ),
        migrations.AddField(
            model_name='subdepartment',
            name='inkrement',
            field=models.CharField(blank=True, help_text='Full description (e.g., Mechanical Design Coordinator)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subdepartment',
            name='role_descrptn',
            field=models.CharField(blank=True, help_text='Full description (e.g., Mechanical Design Coordinator)', max_length=255, null=True),
        ),
    ]
