# Generated by Django 5.2.7 on 2025-12-21 20:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_subdepartment_name_subdepartment_inkrement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subdepartment',
            name='code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='subdepartment',
            name='inkrement',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='subdepartment',
            name='role_descrptn',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='POData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('co_no', models.CharField(db_index=True, max_length=20)),
                ('project_name', models.CharField(max_length=255)),
                ('mat_code', models.CharField(db_index=True, max_length=100)),
                ('po_value_inr', models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(0)])),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'PO Data Entry (Raw)',
                'verbose_name_plural': 'PO Data Entries (Raw)',
                'indexes': [models.Index(fields=['co_no'], name='core_podata_co_no_6dcf79_idx'), models.Index(fields=['mat_code'], name='core_podata_mat_cod_fddf7f_idx'), models.Index(fields=['co_no', 'mat_code'], name='core_podata_co_no_da7755_idx')],
                'constraints': [models.UniqueConstraint(fields=('co_no', 'mat_code', 'po_value_inr'), name='unique_po_line')],
            },
        ),
        migrations.CreateModel(
            name='TimesheetEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('emp_cd', models.CharField(db_index=True, max_length=20)),
                ('emp_name', models.CharField(max_length=100)),
                ('role_description', models.CharField(max_length=255)),
                ('co_no', models.CharField(db_index=True, max_length=20)),
                ('hours', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Timesheet Entry (Raw)',
                'verbose_name_plural': 'Timesheet Entries (Raw)',
                'indexes': [models.Index(fields=['date', 'emp_cd'], name='core_timesh_date_b96bb7_idx'), models.Index(fields=['co_no'], name='core_timesh_co_no_4de029_idx'), models.Index(fields=['date', 'co_no'], name='core_timesh_date_39cce5_idx')],
                'constraints': [models.UniqueConstraint(fields=('date', 'emp_cd', 'role_description', 'co_no', 'hours'), name='unique_timesheet_entry')],
            },
        ),
    ]
