# Generated by Django 5.2.7 on 2025-12-21 20:41

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_subdepartment_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('KTFT', 'Manufacturing parts'), ('KTES', 'Electrical parts (cabinet)'), ('KTEP', 'Electrical parts (periphery)'), ('KTMA', 'Mechanical parts'), ('KTHP', 'Pneumatic parts'), ('ZKE', 'Purchase units'), ('F+V', 'Packing & Transport'), ('SOKO', 'Special costs'), ('RK', 'Travel costs')], max_length=10, unique=True)),
                ('name', models.CharField(editable=False, max_length=255)),
            ],
            options={
                'verbose_name': 'Cost Category',
                'verbose_name_plural': 'Cost Categories',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ProjectCostCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget_cost', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('forecast_cost', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cost_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.costcategory')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_cost_categories', to='core.project')),
            ],
            options={
                'verbose_name': 'Project Cost Category',
                'verbose_name_plural': 'Project Cost Categories',
                'ordering': ['cost_category__code'],
                'unique_together': {('project', 'cost_category')},
            },
        ),
    ]
