# Generated by Django 5.2.7 on 2025-12-22 06:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_costcategory_projectcostcategory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PSRSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateField()),
                ('frequency', models.CharField(choices=[('MONTHLY', 'Monthly'), ('BIWEEKLY', 'Bi-weekly'), ('WEEKLY', 'Weekly')], default='MONTHLY', max_length=20)),
                ('data', models.JSONField(default=dict)),
                ('total_actual_cost', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_prognosis_cost', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_budget_cost', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('overall_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('overall_balance_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='psr_snapshots', to='core.project')),
            ],
            options={
                'verbose_name': 'PSR Snapshot',
                'verbose_name_plural': 'PSR Snapshots',
                'ordering': ['-snapshot_date'],
                'unique_together': {('project', 'snapshot_date')},
            },
        ),
    ]
