# Generated by Django 5.2.7 on 2025-12-23 08:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_subdepartment_budget_cost_subdepartment_budget_hours_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='forecast',
        ),
        migrations.AddField(
            model_name='project',
            name='currency',
            field=models.CharField(choices=[('INR', 'Indian Rupee (₹)'), ('USD', 'US Dollar ($)'), ('EUR', 'Euro (€)'), ('GBP', 'British Pound (£)'), ('CHF', 'Swiss Franc (CHF)')], default='INR', help_text='Project currency for hourly rates and calculations', max_length=3),
        ),
        migrations.AddField(
            model_name='project',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=4, default=1.0, help_text='Exchange rate to INR (manually updated)', max_digits=10, validators=[django.core.validators.MinValueValidator(0.0001)]),
        ),
    ]
