# Generated by Django 5.2.7 on 2025-12-23 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_project_forecast_project_currency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='forecast_cost',
        ),
        migrations.RemoveField(
            model_name='department',
            name='forecast_hours',
        ),
        migrations.RemoveField(
            model_name='projectcostcategory',
            name='forecast_cost',
        ),
        migrations.RemoveField(
            model_name='subdepartment',
            name='forecast_cost',
        ),
        migrations.RemoveField(
            model_name='subdepartment',
            name='forecast_hours',
        ),
        migrations.AddField(
            model_name='psrsnapshot',
            name='total_forecast_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
