# Generated by Django 5.2.7 on 2025-12-23 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_department_forecast_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='costcategory',
            name='mat_code',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
