# Generated by Django 5.2.7 on 2025-12-23 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_costcategory_mat_code'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='podata',
            name='unique_po_line',
        ),
    ]
