# Generated by Django 5.2.7 on 2025-12-24 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_podata_unique_po_line'),
    ]

    operations = [
        migrations.AddField(
            model_name='podata',
            name='description',
            field=models.TextField(blank=True, help_text='Description'),
        ),
        migrations.AddField(
            model_name='podata',
            name='item_code',
            field=models.CharField(blank=True, help_text='ItemCode', max_length=100),
        ),
        migrations.AddField(
            model_name='podata',
            name='po_date',
            field=models.DateField(blank=True, help_text='Po.Date', null=True),
        ),
        migrations.AddField(
            model_name='podata',
            name='po_no',
            field=models.CharField(blank=True, help_text='PoNo', max_length=50),
        ),
        migrations.AddField(
            model_name='podata',
            name='sr_no',
            field=models.PositiveIntegerField(blank=True, help_text='SrNo', null=True),
        ),
        migrations.AddField(
            model_name='podata',
            name='supplier_name',
            field=models.CharField(blank=True, help_text='SupplierName', max_length=255),
        ),
        migrations.AlterField(
            model_name='podata',
            name='co_no',
            field=models.CharField(db_index=True, help_text='CONo', max_length=20),
        ),
        migrations.AlterField(
            model_name='podata',
            name='mat_code',
            field=models.CharField(db_index=True, help_text='MatCode', max_length=100),
        ),
        migrations.AlterField(
            model_name='podata',
            name='project_name',
            field=models.CharField(blank=True, help_text='ProjName', max_length=255),
        ),
        migrations.AddConstraint(
            model_name='podata',
            constraint=models.UniqueConstraint(fields=('co_no', 'po_no', 'sr_no'), name='unique_po_line'),
        ),
    ]
