# Generated by Django 5.2.7 on 2025-12-24 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_podata_description_podata_item_code_podata_po_date_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='timesheetentry',
            name='unique_timesheet_entry',
        ),
        migrations.AddIndex(
            model_name='timesheetentry',
            index=models.Index(fields=['date', 'emp_cd', 'co_no', 'role_description'], name='core_timesh_date_4b00ab_idx'),
        ),
        migrations.AddConstraint(
            model_name='timesheetentry',
            constraint=models.UniqueConstraint(fields=('date', 'emp_cd', 'co_no', 'role_description'), name='unique_timesheet_entry'),
        ),
    ]
