# Generated by Django 5.2.7 on 2025-12-24 06:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_timesheetentry_unique_timesheet_entry_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='subdepartment',
            name='forecast_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='subdepartment',
            name='forecast_hours',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='subdepartment',
            name='forecast_overridden_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subdepartment',
            name='forecast_overridden_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forecast_overrides', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subdepartment',
            name='forecast_override',
            field=models.BooleanField(default=False),
        ),
    ]
