# Generated by Django 5.2.7 on 2025-12-25 06:11

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_forecastadjustment_forecastadjustmentline'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='projectcostcategory',
            name='forecast_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='projectcostcategory',
            name='forecast_overridden_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectcostcategory',
            name='forecast_overridden_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_forecast_overrides', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectcostcategory',
            name='forecast_override',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='MaterialForecastAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjustment_date', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(help_text='Reason for material forecast adjustment')),
                ('previous_forecast_cost', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('new_forecast_cost', models.DecimalField(decimal_places=2, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('adjusted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project_cost_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecast_adjustments', to='core.projectcostcategory')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialForecastAdjustmentLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('adjustment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='core.materialforecastadjustment')),
            ],
        ),
    ]
