# Generated by Django 5.2.7 on 2025-12-26 07:00

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_projectcostcategory_forecast_cost_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='currency',
            field=models.CharField(choices=[('INR', 'Indian Rupee (₹)'), ('USD', 'US Dollar ($)'), ('EUR', 'Euro (€)'), ('GBP', 'British Pound (£)'), ('CHF', 'Swiss Franc (CHF)')], default='INR', max_length=3),
        ),
        migrations.AlterField(
            model_name='project',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=4, default=1.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0001)]),
        ),
        migrations.CreateModel(
            name='SubDepartmentBudgetAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjustment_date', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(help_text='Reason for budget hours adjustment')),
                ('previous_budget_hours', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('new_budget_hours', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('adjusted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('sub_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_adjustments', to='core.subdepartment')),
            ],
            options={
                'verbose_name': 'Sub-Department Budget Adjustment',
                'verbose_name_plural': 'Sub-Department Budget Adjustments',
                'ordering': ['-adjustment_date'],
            },
        ),
    ]
