# Generated by Django 5.2.7 on 2025-12-26 09:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_project_currency_alter_project_exchange_rate_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCostCategoryBudgetAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjustment_date', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(help_text='Reason for budget cost adjustment')),
                ('previous_budget_cost', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('new_budget_cost', models.DecimalField(decimal_places=2, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('adjusted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project_cost_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_adjustments', to='core.projectcostcategory')),
            ],
            options={
                'verbose_name': 'Project Cost Category Budget Adjustment',
                'verbose_name_plural': 'Project Cost Category Budget Adjustments',
                'ordering': ['-adjustment_date'],
            },
        ),
    ]
