# Generated by Django 5.2.7 on 2025-12-29 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_projectcostcategorybudgetadjustment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costcategory',
            name='code',
            field=models.CharField(choices=[('KTFT', 'KTFT Manufacturing parts'), ('KTES', 'KTES Electrical parts (cabinet)'), ('KTEP', 'KTEP Electrical parts (periphery)'), ('KTMA', 'KTMA Mechanical parts'), ('KTHP', 'KTHP Pneumatic parts'), ('ZKE', 'ZKE Purchase units'), ('F+V', 'F_V Packing & Transport'), ('SOKO', 'SOKO Special costs'), ('RK', 'RK Travel costs')], max_length=10, unique=True),
        ),
    ]
