# Generated by Django 5.2.7 on 2025-12-29 09:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_costcategory_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='eff',
        ),
        migrations.RemoveField(
            model_name='project',
            name='factor',
        ),
        migrations.RemoveField(
            model_name='project',
            name='margin',
        ),
        migrations.RemoveField(
            model_name='project',
            name='ter',
        ),
        migrations.AddField(
            model_name='project',
            name='eff_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='EFF (%)'),
        ),
        migrations.AddField(
            model_name='project',
            name='ter_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='TER (%)'),
        ),
    ]
