# Generated by Django 5.2.7 on 2025-12-30 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_costcategory_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costcategory',
            name='code',
            field=models.CharField(choices=[('KTFT', 'KTFT Manufacturing parts'), ('KTES', 'KTES Electrical parts (cabinet)'), ('KTEP', 'KTEP Electrical parts (periphery)'), ('KTMA', 'KTMA Mechanical parts'), ('KTHP', 'KTHP Pneumatic parts'), ('ZKE', 'ZKE Purchase units'), ('F+V', 'F_V Packing & Transport'), ('SOKO', 'SOKO Special costs'), ('RK', 'RK Travel costs'), ('ASSEMBLY SERVICES', 'ASSEMBLY SERVICES'), ('DESIGN SERVICES', 'DESIGN SERVICE'), ('STATIONARY', 'STATIONARY'), ('QUALITY CHECKING', 'QC (QUALITY CHECKING SERVICES)'), ('FACTORY EQUIPMENTS CONSUMABLES', 'FACTORY EQUIPMENTS CONSUMABLES')], max_length=200, unique=True),
        ),
    ]
