# Generated by Django 5.2.7 on 2025-12-30 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_costcategory_code'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='timesheetentry',
            name='unique_timesheet_entry',
        ),
        migrations.AddConstraint(
            model_name='timesheetentry',
            constraint=models.UniqueConstraint(fields=('date', 'emp_cd', 'co_no', 'role_description', 'hours'), name='unique_timesheet_entry'),
        ),
    ]
