# Generated by Django 5.2.7 on 2025-12-31 04:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_remove_timesheetentry_unique_timesheet_entry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectcostcategory',
            name='baseline_budget_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AddField(
            model_name='subdepartment',
            name='baseline_budget_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
