# Generated by Django 5.2.7 on 2025-12-31 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_projectcostcategory_baseline_budget_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='psrsnapshot',
            name='labor_actual_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='psrsnapshot',
            name='labor_actual_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='psrsnapshot',
            name='labor_budget_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='psrsnapshot',
            name='labor_budget_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='psrsnapshot',
            name='labor_forecast_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='psrsnapshot',
            name='labor_forecast_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='psrsnapshot',
            name='labor_prognosis_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='psrsnapshot',
            name='labor_prognosis_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='psrsnapshot',
            name='material_actual_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='psrsnapshot',
            name='material_budget_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='psrsnapshot',
            name='material_forecast_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='psrsnapshot',
            name='material_prognosis_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
