# Generated by Django 5.2.7 on 2026-01-03 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_psrsnapshot_labor_actual_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='psrsnapshot',
            name='eff_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='psrsnapshot',
            name='factor',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='psrsnapshot',
            name='margin',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='psrsnapshot',
            name='sum_prognosis',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='psrsnapshot',
            name='ter_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
