# Generated by Django 5.2.7 on 2026-01-03 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_psrsnapshot_eff_value_psrsnapshot_factor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='psrsnapshot',
            name='overall_balance',
        ),
        migrations.RemoveField(
            model_name='psrsnapshot',
            name='overall_balance_percentage',
        ),
    ]
