# Generated by Django 5.2.7 on 2026-01-03 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_remove_psrsnapshot_overall_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='current_phase',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='cw_no',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='settlement_peroid',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
