# Generated by Django 5.2.7 on 2026-01-03 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_project_current_phase_project_cw_no_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='settlement_peroid',
            new_name='settlement_period',
        ),
    ]
