# Generated by Django 5.2.7 on 2026-01-03 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_rename_settlement_peroid_project_settlement_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='current_phase',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='cw_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='settlement_period',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
