# Generated by Django 6.0 on 2026-01-03 21:01

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_alter_project_current_phase_alter_project_cw_no_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='projectcostcategory',
            name='actual_override',
            field=models.BooleanField(default=False, help_text='If true, use manual actuals for RK instead of PO'),
        ),
        migrations.CreateModel(
            name='RKActualAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(help_text='Reason for entering manual actuals')),
                ('adjusted_at', models.DateTimeField(auto_now_add=True)),
                ('adjusted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project_cost_category', models.ForeignKey(limit_choices_to={'cost_category__code': 'RK'}, on_delete=django.db.models.deletion.CASCADE, related_name='rk_actual_adjustments', to='core.projectcostcategory')),
            ],
            options={
                'verbose_name': 'RK Actual Adjustment',
                'verbose_name_plural': 'RK Actual Adjustments',
                'ordering': ['-adjusted_at'],
            },
        ),
        migrations.CreateModel(
            name='RKActualAdjustmentLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('adjustment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='core.rkactualadjustment')),
            ],
            options={
                'verbose_name': 'RK Actual Line',
                'verbose_name_plural': 'RK Actual Lines',
            },
        ),
    ]
