# Generated by Django 5.2.7 on 2026-01-05 07:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_projectcostcategory_actual_override_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='actual_budget',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=15),
        ),
        migrations.AddField(
            model_name='project',
            name='cost_with_sgna',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=15),
        ),
        migrations.AddField(
            model_name='project',
            name='direct_margin_percentage',
            field=models.DecimalField(decimal_places=4, default=0.0, editable=False, max_digits=8),
        ),
        migrations.AddField(
            model_name='project',
            name='direct_margin_value',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=15),
        ),
        migrations.AddField(
            model_name='project',
            name='ebit_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='EBIT (%)'),
        ),
        migrations.AddField(
            model_name='project',
            name='ebit_value',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=15),
        ),
        migrations.AddField(
            model_name='project',
            name='eff_value',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=15),
        ),
        migrations.AddField(
            model_name='project',
            name='factor',
            field=models.DecimalField(decimal_places=4, default=0.0, editable=False, max_digits=8),
        ),
        migrations.AddField(
            model_name='project',
            name='hk',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=15, verbose_name='HK (House Keeping)'),
        ),
        migrations.AddField(
            model_name='project',
            name='sgna_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='SGNA (%)'),
        ),
        migrations.AddField(
            model_name='project',
            name='ter_value',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=15),
        ),
        migrations.AlterField(
            model_name='project',
            name='budget',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=15),
        ),
    ]
