# Generated by Django 5.2.7 on 2026-01-05 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_project_actual_budget_project_cost_with_sgna_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='sgna_value',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=15),
        ),
    ]
