# Generated by Django 5.2.7 on 2026-01-05 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_project_sgna_value'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='timesheetentry',
            name='unique_timesheet_entry',
        ),
        migrations.AddConstraint(
            model_name='timesheetentry',
            constraint=models.UniqueConstraint(fields=('date', 'emp_cd', 'co_no', 'role_description'), name='unique_timesheet_entry'),
        ),
    ]
