# Generated by Django 5.2.7 on 2026-01-05 12:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_subdepartment_baseline_budget_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='sales_value_inr',
            field=models.DecimalField(decimal_places=2, default=100000000, max_digits=15, validators=[django.core.validators.MinValueValidator(0.0)]),
            preserve_default=False,
        ),
    ]
