# Generated by Django 5.2.7 on 2026-01-05 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_project_sales_value_inr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='sales_value_inr',
        ),
    ]
