# Generated by Django 5.2.7 on 2026-01-07 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_remove_project_sales_value_inr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='factor',
            field=models.DecimalField(decimal_places=3, default=0.0, editable=False, max_digits=8),
        ),
    ]
