# Generated by Django 5.2.7 on 2026-01-07 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_alter_project_factor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psrsnapshot',
            name='factor',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=8),
        ),
    ]
