# Generated by Django 5.2.7 on 2026-01-07 09:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_alter_psrsnapshot_factor'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='sales_value_foreign_curr',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
